(function () {
    'use strict';
	var  countries = [ 
	{ "name" : "Afghanistan", "short" : "AF", "code": "+93"},
	{"name" : "Albania ","short" : "AL",	"code" : "+355" },
	{"name" : "Algeria ", "short" : "DZ", "code" : "+213"},
	{"name" : "American Samoa", "short" : "AS", "code" : "+1-684"},
	{"name" : "Andorra, Principality of ", "short" : "AD", "code" : "+376"},
	{"name" : "Angola", "short" : "AO", "code" : "+244"},
	{"name" : "Anguilla ", "short" : "AI", "code" : "+1-264"},
	{"name" : "Antarctica", "short" : "AQ", "code" : "+672"},
	{"name" : "Antigua and Barbuda", "short" : "AG", "code" : "+1-268"},
	{"name" : "Argentina ", "short" : "AR", "code" : "+54"},
	{"name" : "Armenia", "short" : "AM", "code" : "+374"},
	{"name" : "Aruba", "short" : "AW", "code" : "+297"},
	{"name" : "Australia", "short" : "AU", "code" : "+61"},
	{"name" : "Austria", "short" : "AT", "code" : "+43"},
	{"name" : "Bahamas, Commonwealth of The" , "short" : "BS" , "code" : "+1-242"},
	{"name" : "Bahrain, Kingdom of (Former Dilmun)" , "short" : "BH" , "code" : "+973"},
	{"name" : "Bangladesh (Former East Pakistan)" , "short" : "BD" , "code" : "+880"},
	{"name" : "Barbados" , "short" : "BB" , "code" : "+1-246"},
	{"name" : "Belarus (Former Belorussian [Byelorussian] Soviet Socialist Republic)" , "short" : "BY" , "code" : "+375"},
	{"name" : "Azerbaijan or Azerbaidjan (Former Azerbaijan Soviet Socialist Republic)", "short" : "AZ", "code" : "+994"},
	{"name" : "Belgium" , "short" : "BE" , "code" : "+32"},
	{"name" : "Belize (Former British Honduras)" , "short" : "BZ" , "code" : "+501"},
	{"name" : "Benin (Former Dahomey)" , "short" : "BJ" , "code" : "+229"},
	{"name" : "Bermuda" , "short" : "BM" , "code" : "+1-441"},
	{"name" : "Bhutan, Kingdom of" , "short" : "BT" , "code" : "+975"},
	{"name" : "Bolivia" , "short" : "BO" , "code" : "+591"},
	{"name" : "Bosnia and Herzegovina" , "short" : "BA" , "code" : "+387"},
	{"name" : "Botswana (Former Bechuanaland)" , "short" : "BW" , "code" : "+267"},
	{"name" : "Bouvet Island (Territory of Norway)" , "short" : "BV" , "code" : ""},
	{"name" : "Brazil" , "short" : "BR" , "code" : "+55"},
	{"name" : "British Indian Ocean Territory (BIOT)" , "short" : "IO" , "code" : ""},
	{"name" : "Brunei (Negara Brunei Darussalam)" , "short" : "BN" , "code" : "+673"},
	{"name" : "Bulgaria" , "short" : "BG" , "code" : "+359"},
	{"name" : "Burkina Faso (Former Upper Volta)" , "short" : "BF" , "code" : "+226"},
	{"name" : "Burundi (Former Urundi)" , "short" : "BI" , "code" : "+257"},
	{"name" : "Cambodia, Kingdom of (Former Khmer Republic, Kampuchea Republic)" , "short" : "KH" , "code" : "+855"},
	{"name" : "Cameroon (Former French Cameroon)" , "short" : "CM" , "code" : "+237"},
	{"name" : "Canada" , "short" : "CA" , "code" : "+1"},
	{"name" : "Cape Verde" , "short" : "CV" , "code" : "+238"},
	{"name" : "Cayman Islands" , "short" : "KY" , "code" : "+1-345"},
	{"name" : "Central African Republic" , "short" : "CF" , "code" : "+236"},
	{"name" : "Chad" , "short" : "TD" , "code" : "+235"},
	{"name" : "Chile" , "short" : "CL" , "code" : "+56"},
	{"name" : "China" , "short" : "CN" , "code" : "+86"},
	{"name" : "Christmas Island" , "short" : "CX" , "code" : "+53"},
	{"name" : "Cocos (Keeling) Islands" , "short" : "CC" , "code" : "+61"},
	{"name" : "Colombia" , "short" : "CO" , "code" : "+57"},
	{"name" : "Comoros, Union of the" , "short" : "KM" , "code" : "+269"},
	{"name" : "Congo, Democratic Republic of the (Former Zaire)" , "short" : "CD" , "code" : "+243"},
	{"name" : "Congo, Republic of the" , "short" : "CG" , "code" : "+242"},
	{"name" : "Cook Islands (Former Harvey Islands)" , "short" : "CK" , "code" : "+682"},
	{"name" : "Costa Rica" , "short" : "CR" , "code" : "+506"},
	{"name" : "Cote D'Ivoire (Former Ivory Coast)" , "short" : "CI" , "code" : "+225"},
	{"name" : "Croatia (Hrvatska)" , "short" : "HR" , "code" : "+385"},
	{"name" : "Cuba" , "short" : "CU" , "code" : "+53"},
	{"name" : "Cyprus" , "short" : "CY" , "code" : "+357"},
	{"name" : "Czech Republic" , "short" : "CZ" , "code" : "+420"},
	{"name" : "Denmark" , "short" : "DK" , "code" : "+45"},
	{"name" : "Djibouti (Former French Territory of the Afars and Issas, French Somaliland)" , "code" : "DJ" , "code" : "+253"},
	{"name" : "Dominica" , "short" : "DM" , "code" : "+1-767"},
	{"name" : "Dominican Republic" , "short" : "DO" , "code" : "+1-809 and +1-829  "},
	{"name" : "East Timor (Former Portuguese Timor)" , "short" : "TP" , "code" : "+670"},
	{"name" : "Ecuador" , "short" : "EC" , "code" : "+593 "},
	{"name" : "Egypt (Former United Arab Republic - with Syria)" , "short" : "EG" , "code" : "+20"},
	{"name" : "El Salvador" , "short" : "SV" , "code" : "+503"},
	{"name" : "Equatorial Guinea (Former Spanish Guinea)" , "short" : "GQ" , "code" : "+240"},
	{"name" : "Eritrea (Former Eritrea Autonomous Region in Ethiopia)" , "short" : "ER" , "code" : "+291"},
	{"name" : "Estonia (Former Estonian Soviet Socialist Republic)" , "short" : "EE" , "code" : "+372"},
	{"name" : "Ethiopia (Former Abyssinia, Italian East Africa)" , "short" : "ET" , "code" : "+251"},
	{"name" : "Falkland Islands (Islas Malvinas)" , "short" : "FK" , "code" : "+500"},
	{"name" : "Faroe Islands" , "short" : "FO" , "code" : "+298"},
	{"name" : "Fiji" , "short" : "FJ" , "code" : "+679"},
	{"name" : "Finland" , "short" : "FI" , "code" : "+358"},
	{"name" : "France" , "short" : "FR" , "code" : "+33"},
	{"name" : "French Guiana or French Guyana" , "short" : "GF" , "code" : "+594"},
	{"name" : "French Polynesia (Former French Colony of Oceania)" , "short" : "PF" , "code" : "+689"},
	{"name" : "Gabon (Gabonese Republic)" , "short" : "GA" , "code" : "+241"},
	{"name" : "Gambia, The" , "short" : "GM" , "code" : "+220"},
	{"name" : "Georgia (Former Georgian Soviet Socialist Republic)" , "short" : "GE" , "code" : "+995"},
	{"name" : "Germany" , "short" : "DE" , "code" : "+49"},
	{"name" : "Ghana (Former Gold Coast)" , "short" : "GH" , "code" : "+233"},
	{"name" : "Gibraltar" , "short" : "GI" , "code" : "+350"},
	{"name" : "Great Britain (United Kingdom)" , "short" : "GB" , "code" : "+44"},
	{"name" : "Greece" , "short" : "GR" , "code" : "+30"},
	{"name" : "Greenland" , "short" : "GL" , "code" : "+299"},
	{"name" : "Grenada" , "short" : "GD" , "code" : "+1-473"},
	{"name" : "Guadeloupe" , "short" : "GP" , "code" : "+590"},
	{"name" : "Guam" , "short" : "GU" , "code" : "+1-671"},
	{"name" : "Guatemala" , "short" : "GT" , "code" : "+502"},
	{"name" : "Guinea (Former French Guinea)" , "short" : "GN" , "code" : "+224"},
	{"name" : "Guinea-Bissau (Former Portuguese Guinea)" , "short" : "GW" , "code" : "+245"},
	{"name" : "Guyana (Former British Guiana)" , "short" : "GY" , "code" : "+592"},
	{"name" : "Haiti" , "short" : "HT" , "code" : "+509"},
	{"name" : "Heard Island and McDonald Islands (Territory of Australia)" , "short" : "HM" , "code" : ""},
	{"name" : "Holy See (Vatican City State)" , "short" : "VA" , "code" : ""},
	{"name" : "Honduras" , "short" : "HN" , "code" : "+504"},
	{"name" : "Hong Kong" , "short" : "HK" , "code" : "+852"},
	{"name" : "Hungary" , "short" : "HU" , "code" : "+36"},
	{"name" : "Iceland" , "short" : "IS" , "code" : "+354"},
	{"name" : "India" , "short" : "IN" , "code" : "+91"},
	{"name" : "Indonesia (Former Netherlands East Indies; Dutch East Indies)" , "short" : "ID" , "code" : "+62"},
	{"name" : "Iran, Islamic Republic of" , "short" : "IR" , "code" : "+98"},
	{"name" : "Iraq" , "short" : "IQ" , "code" : "+964"},
	{"name" : "Ireland" , "short" : "IE" , "code" : "+353"},
	{"name" : "Israel" , "short" : "IL" , "code" : "+972"},
	{"name" : "Italy" , "short" : "IT" , "code" : "+39"},
	{"name" : "Jamaica" , "short" : "JM" , "code" : "+1-876"},
	{"name" : "Japan" , "short" : "JP" , "code" : "+81"},
	{"name" : "Jordan (Former Transjordan)" , "short" : "JO" , "code" : "+962"},
	{"name" : "Kazakstan or Kazakhstan (Former Kazakh Soviet Socialist Republic)" , "short" : "KZ" , "code" : "+7"},
	{"name" : "Kenya (Former British East Africa)" , "short" : "KE" , "code" : "+254"},
	{"name" : "Kiribati (Pronounced keer-ree-bahss) (Former Gilbert Islands)" , "short" : "KI" , "code" : "+686"},
	{"name" : "Korea, Democratic People's Republic of (North Korea)" , "short" : "KP" , "code" : "+850"},
	{"name" : "Korea, Republic of (South Korea)" , "short" : "KR" , "code" : "+82"},
	{"name" : "Kuwait" , "short" : "KW" , "code" : "+965"},
	{"name" : "Kyrgyzstan (Kyrgyz Republic) (Former Kirghiz Soviet Socialist Republic)" , "short" : "KG" , "code" : "+996"},
	{"name" : "Lao People's Democratic Republic (Laos)" , "short" : "LA" , "code" : "+856"},
	{"name" : "Latvia (Former Latvian Soviet Socialist Republic)" , "short" : "LV" , "code" : "+371"},
	{"name" : "Lebanon" , "short" : "LB" , "code" : "+961"},
	{"name" : "Lesotho (Former Basutoland)" , "short" : "LS" , "code" : "+266"},
	{"name" : "Liberia" , "short" : "LR" , "code" : "+231"},
	{"name" : "Libya (Libyan Arab Jamahiriya)" , "short" : "LY" , "code" : "+218"},
	{"name" : "Liechtenstein" , "short" : "LI" , "code" : "+423"},
	{"name" : "Lithuania (Former Lithuanian Soviet Socialist Republic)" , "short" : "LT" , "code" : "+370"},
	{"name" : "Luxembourg" , "short" : "LU" , "code" : "+352"},
	{"name" : "Macau" , "short" : "MO" , "code" : "+853"},
	{"name" : "Macedonia, The Former Yugoslav Republic of" , "short" : "MK" , "code" : "+389"},
	{"name" : "Madagascar (Former Malagasy Republic)" , "short" : "MG" , "code" : "+261"},
	{"name" : "Malawi (Former British Central African Protectorate, Nyasaland)" , "short" : "MW" , "code" : "+265"},
	{"name" : "Malaysia" , "short" : "MY" , "code" : "+60"},
	{"name" : "Maldives" , "short" : "MV" , "code" : "+960"},
	{"name" : "Mali (Former French Sudan and Sudanese Republic)" , "short" : "ML" , "code" : "+223"},
	{"name" : "Malta" , "short" : "MT" , "code" : "+356"},
	{"name" : "Marshall Islands (Former Marshall Islands District - Trust Territory of the Pacific Islands)" , "short" : "MH" , "code" : "+692"},
	{"name" : "Martinique (French)" , "short" : "MQ" , "code" : "+596"},
	{"name" : "Mauritania" , "short" : "MR" , "code" : "+222"},
	{"name" : "Mauritius" , "short" : "MU" , "code" : "+230"},
	{"name" : "Mayotte (Territorial Collectivity of Mayotte)" , "short" : "YT" , "code" : "+269"},
	{"name" : "Mexico" , "short" : "MX" , "code" : "+52"},
	{"name" : "Micronesia, Federated States of (Former Ponape, Truk, and Yap Districts - Trust Territory of the Pacific Islands)" , "short" : "FM" , "code" : "+691"},
	{"name" : "Moldova, Republic of" , "short" : "MD" , "code" : "+373"},
	{"name" : "Monaco, Principality of" , "short" : "MC" , "code" : "+377"},
	{"name" : "Mongolia (Former Outer Mongolia)" , "short" : "MN" , "code" : "+976"},
	{"name" : "Montserrat" , "short" : "MS" , "code" : "+1-664"},
	{"name" : "Morocco" , "short" : "MA" , "code" : "+212"},
	{"name" : "Mozambique (Former Portuguese East Africa)" , "short" : "MZ" , "code" : "+258"},
	{"name" : "Myanmar, Union of (Former Burma)" , "short" : "MM" , "code" : "+95"},
	{"name" : "Namibia (Former German Southwest Africa, South-West Africa)" , "short" : "NA" , "code" : "+264"},
	{"name" : "Nauru (Former Pleasant Island)" , "short" : "NR" , "code" : "+674"},
	{"name" : "Nepal" , "short" : "NP" , "code" : "+977"},
	{"name" : "Netherlands" , "short" : "NL" , "code" : "+31"},
	{"name" : "Netherlands Antilles (Former Curacao and Dependencies)" , "short" : "AN" , "code" : "+599"},
	{"name" : "New Caledonia" , "short" : "NC" , "code" : "+687"},
	{"name" : "New Zealand (Aotearoa)" , "short" : "NZ" , "code" : "+64"},
	{"name" : "Nicaragua" , "short" : "NI" , "code" : "+505"},
	{"name" : "Niger" , "short" : "NE" , "code" : "+227"},
	{"name" : "Nigeria" , "short" : "NG" , "code" : "+234"},
	{"name" : "Niue (Former Savage Island)" , "short" : "NU" , "code" : "+683"},
	{"name" : "Norfolk Island" , "short" : "NF" , "code" : "+672"},
	{"name" : "Northern Mariana Islands (Former Mariana Islands District - Trust Territory of the Pacific Islands)" , "short" : "MP" , "code" : "+1-670"},
	{"name" : "Norway" , "short" : "NO" , "code" : "+47"},
	{"name" : "Oman, Sultanate of (Former Muscat and Oman)" , "short" : "OM" , "code" : "+968"},
	{"name" : "Pakistan (Former West Pakistan)" , "short" : "PK" , "code" : "+92"},
	{"name" : "Palau (Former Palau District - Trust Terriroty of the Pacific Islands)" , "short" : "PW" , "code" : "+680"},
	{"name" : "Palestinian State (Proposed)" , "short" : "PS" , "code" : "+970"},
	{"name" : "Panama" , "short" : "PA" , "code" : "+507"},
	{"name" : "Papua New Guinea (Former Territory of Papua and New Guinea)" , "short" : "PG" , "code" : "+675"},
	{"name" : "Paraguay" , "short" : "PY" , "code" : "+595"},
	{"name" : "Peru" , "short" : "PE" , "code" : "+51"},
	{"name" : "Philippines" , "short" : "PH" , "code" : "+63"},
	{"name" : "Pitcairn Island" , "short" : "PN" , "code" : ""},
	{"name" : "Poland" , "short" : "PL" , "code" : "+48"},
	{"name" : "Portugal" , "short" : "PT" , "code" : "+351"},
	{"name" : "Puerto Rico" , "short" : "PR" , "code" : "+1-787 or +1-939"},
	{"name" : "Qatar, State of" , "short" : "QA" , "code" : "+974 "},
	{"name" : "Reunion (French) (Former Bourbon Island)" , "code" : "RE" , "code" : "+262"},
	{"name" : "Romania" , "short" : "RO" , "code" : "+40"},
	{"name" : "Russia - USSR (Former Russian Empire, Union of Soviet Socialist Republics, Russian Soviet Federative Socialist Republic) Now RU - Russian Federation" , "short" : "SU" , "code" : "+7"},
	{"name" : "Russian Federation" , "short" : "RU" , "code" : "+7"},
	{"name" : "Rwanda (Rwandese Republic) (Former Ruanda)" , "short" : "RW" , "code" : "+250"},
	{"name" : "Saint Helena" , "short" : "SH" , "code" : "+290"},
	{"name" : "Saint Kitts and Nevis (Former Federation of Saint Christopher and Nevis)" , "short" : "KN" , "code" : "+1-869"},
	{"name" : "Saint Lucia" , "short" : "LC" , "code" : "+1-758"},
	{"name" : "Saint Pierre and Miquelon" , "short" : "PM" , "code" : "+508"},
	{"name" : "Saint Vincent and the Grenadines" , "short" : "VC" , "code" : "+1-784"},
	{"name" : "Samoa (Former Western Samoa)" , "short" : "WS" , "code" : "+685"},
	{"name" : "San Marino" , "short" : "SM" , "code" : "+378"},
	{"name" : "Sao Tome and Principe" , "short" : "ST" , "code" : "+239"},
	{"name" : "Saudi Arabia" , "short" : "SA" , "code" : "+966"},
	{"name" : "Serbia, Republic of" , "short" : "RS" , "code" : "+381"},
	{"name" : "Senegal" , "short" : "SN" , "code" : "+221"},
	{"name" : "Seychelles" , "short" : "SC" , "code" : "+248"},
	{"name" : "Sierra Leone" , "short" : "SL" , "code" : "+232"},
	{"name" : "Singapore" , "short" : "SG" , "code" : "+65"},
	{"name" : "Slovakia" , "short" : "SK" , "code" : "+421"},
	{"name" : "Slovenia" , "short" : "SI" , "code" : "+386"},
	{"name" : "Solomon Islands (Former British Solomon Islands)" , "short" : "SB" , "code" : "+677"},
	{"name" : "Somalia (Former Somali Republic, Somali Democratic Republic)" , "short" : "SO" , "code" : "+252"},
	{"name" : "South Africa (Former Union of South Africa)" , "short" : "ZA" , "code" : "+27"},
	{"name" : "South Georgia and the South Sandwich Islands" , "short" : "GS" , "code" : ""},
	{"name" : "Spain" , "short" : "ES" , "code" : "+34"},
	{"name" : "Sri Lanka (Former Serendib, Ceylon)" , "short" : "LK" , "code" : "+94"},
	{"name" : "Sudan (Former Anglo-Egyptian Sudan)" , "short" : "SD" , "code" : "+249"},
	{"name" : "Suriname (Former Netherlands Guiana, Dutch Guiana)" , "short" : "SR" , "code" : "+597"},
	{"name" : "Svalbard (Spitzbergen) and Jan Mayen Islands" , "short" : "SJ" , "code" : ""},
	{"name" : "Swaziland, Kingdom of" , "short" : "SZ" , "code" : "+268"},
	{"name" : "Sweden" , "short" : "SE" , "code" : "+46"},
	{"name" : "Switzerland" , "short" : "CH" , "code" : "+41"},
	{"name" : "Syria (Syrian Arab Republic) (Former United Arab Republic - with Egypt)" , "short" : "SY" , "code" : "+963"},
	{"name" : "Taiwan (Former Formosa)" , "short" : "TW" , "code" : "+886"},
	{"name" : "Tajikistan (Former Tajik Soviet Socialist Republic)" , "short" : "TJ" , "code" : "+992"},
	{"name" : "Tanzania, United Republic of (Former United Republic of Tanganyika and Zanzibar)" , "short" : "TZ" , "code" : "+255"},
	{"name" : "Thailand (Former Siam)" , "short" : "TH" , "code" : "+66"},
	{"name" : "Togo (Former French Togoland)" , "short" : "TG" , "code" : ""},
	{"name" : "Tokelau" , "short" : "TK" , "code" : "+690"},
	{"name" : "Tonga, Kingdom of (Former Friendly Islands)" , "short" : "TO" , "code" : "+676"},
	{"name" : "Trinidad and Tobago" , "short" : "TT" , "code" : "+1-868"},
	{"name" : "Tromelin Island" , "short" : "TE" , "code" : ""},
	{"name" : "Tunisia" , "short" : "TN" , "code" : "+216"},
	{"name" : "Turkey" , "short" : "TR" , "code" : "+90"},
	{"name" : "Turkmenistan (Former Turkmen Soviet Socialist Republic)" , "short" : "TM" , "code" : "+993"},
	{"name" : "Turks and Caicos Islands" , "short" : "TC" , "code" : "+1-649"},
	{"name" : "Tuvalu (Former Ellice Islands)" , "short" : "TV" , "code" : "+688"},
	{"name" : "Uganda, Republic of" , "short" : "UG" , "code" : "+256"},
	{"name" : "Ukraine (Former Ukrainian National Republic, Ukrainian State, Ukrainian Soviet Socialist Republic)" , "short" : "UA" , "code" : "+380"},
	{"name" : "United Arab Emirates (UAE) (Former Trucial Oman, Trucial States)" , "short" : "AE" , "code" : "+971"},
	{"name" : "United Kingdom (Great Britain / UK)" , "short" : "GB" , "code" : "+44"},
	{"name" : "United States" , "short" : "US" , "code" : "+1"},
	{"name" : "United States Minor Outlying Islands" , "short" : "UM" , "code" : ""},
	{"name" : "Uruguay, Oriental Republic of (Former Banda Oriental, Cisplatine Province)" , "short" : "UY" , "code" : "+598"},
	{"name" : "Uzbekistan (Former UZbek Soviet Socialist Republic)" , "short" : "UZ" , "code" : "+998"},
	{"name" : "Vanuatu (Former New Hebrides)" , "short" : "VU" , "code" : "+678"},
	{"name" : "Vatican City State (Holy See)" , "short" : "VA" , "code" : "+418"},
	{"name" : "Venezuela" , "short" : "VE" , "code" : "+58"},
	{"name" : "Vietnam" , "short" : "VN" , "code" : "+84"},
	{"name" : "Virgin Islands, British" , "short" : "VI" , "code" : "+1-284"},
	{"name" : "Virgin Islands, United States (Former Danish West Indies)" , "short" : "VQ" , "code" : "+1-340"},
	{"name" : "Wallis and Futuna Islands" , "short" : "WF" , "code" : "+681"},
	{"name" : "Yemen" , "short" : "YE" , "code" : "+967"},
	{"name" : "Zambia, Republic of (Former Northern Rhodesia)" , "short" : "ZM" , "code" : "+260"},
	{"name" : "Zimbabwe, Republic of (Former Southern Rhodesia, Rhodesia)" , "short" : "ZW" , "code" : "+263" , "code" : ""}
	 ];


    
    angular.module('CountryCall', [])
    .controller('CountryController', CountryController);
    
    function CountryController($scope) {
	  $scope.countries = countries ;
    }
    
    })();
